project:
  type: book
  pre-render: setup.R

book:
  title: "ggiraph-book"
  author: "ArData"
  date: "2023-01-22"
  twitter-card: true
  repo-url: https://github.com/ardata-fr/ggiraph-book/
  site-url: https://ardata-fr.github.io/ggiraph-book
  sharing: [twitter, facebook]
  favicon: assets/img/favicon.png
  cover-image: assets/img/ggiraph-logo.png
  cover-image-alt: ggiraph hexagonal logo
  chapters:
    - index.qmd
    - starting.qmd
    - part: ggiraph-simple-use.qmd
      chapters:
      - customize.qmd
      - fonts.qmd
      - size.qmd
      - toolbar.qmd
      - examples.qmd
      - extra-ipar.qmd
    - part: ggiraph-shiny.qmd
      chapters:
      - selections.qmd
      - shiny.qmd
      - shiny-examples.qmd
  page-footer:
    left: |
      The ggiraph book was written by David Gohel.
    right: |
      package 'ggiraph' is proudly brought to you by <a href="http://www.ardata.fr" class="external-link"><img alt="ardata" src="assets/img/ardata-logo.svg" style="vertical-align:middle;height:24px;"></a>.

format:
  html:
    theme: cosmo
    code-copy: true

editor: source

