---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
library(ggiraph)
library(magrittr)

dataset = iris
dataset$tooltip = dataset$Species
dataset$clickjs = paste0("alert(\"",dataset$Species, "\")" )

# plots
gg_point = ggplot(dataset, aes(x = Sepal.Length, y = Petal.Width,
                               color = Species, tooltip = tooltip, onclick = clickjs) ) +
  geom_point_interactive() + theme_dark()

ggiraph(code = {print(gg_point)}, zoom_max = 4, flexdashboard = TRUE) 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
gg_point = ggplot(dataset, aes(x = Sepal.Length, y = Petal.Width,
                               color = Species, tooltip = tooltip, onclick = clickjs) ) +
  geom_point_interactive() + theme_linedraw()

ggiraph(code = {print(gg_point)}, zoom_max = 1, flexdashboard = TRUE) 
```

### Chart C

```{r}

```

