# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DSVG_ <- function(file, width, height, bg, pointsize, standalone, setdims, canvas_id, aliases) {
    .Call(`_ggiraph_DSVG_`, file, width, height, bg, pointsize, standalone, setdims, canvas_id, aliases)
}

set_tracer_on <- function(dn) {
    .Call(`_ggiraph_set_tracer_on`, dn)
}

set_tracer_off <- function(dn) {
    .Call(`_ggiraph_set_tracer_off`, dn)
}

collect_id <- function(dn) {
    .Call(`_ggiraph_collect_id`, dn)
}

add_attribute <- function(dn, id, str, name) {
    .Call(`_ggiraph_add_attribute`, dn, id, str, name)
}

