# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DSVG_ <- function(filename, width, height, canvas_id, standalone, setdims, pointsize, bg, aliases) {
    .Call(`_ggiraph_DSVG_`, filename, width, height, canvas_id, standalone, setdims, pointsize, bg, aliases)
}

set_tracer_on <- function(dn) {
    .Call(`_ggiraph_set_tracer_on`, dn)
}

set_tracer_off <- function(dn) {
    .Call(`_ggiraph_set_tracer_off`, dn)
}

collect_id <- function(dn) {
    .Call(`_ggiraph_collect_id`, dn)
}

add_attribute <- function(dn, name, ids, values) {
    .Call(`_ggiraph_add_attribute`, dn, name, ids, values)
}

non_overlapping_texts <- function(dn, label, x, y, hjust, vjust, rot, fontsize, fontfamily, fontface, lineheight) {
    .Call(`_ggiraph_non_overlapping_texts`, dn, label, x, y, hjust, vjust, rot, fontsize, fontfamily, fontface, lineheight)
}

